import Head from "next/head";
import Message from "@/components/message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "@firebase/firestore";
import Link from "next/link";

export default function Home() {
  //Create a state with all the post
  const [allPost, setAllPosts] = useState([]);

  //this constantly searching for chnages to update
  const getPost = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPost();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen items-center justify-center my-12 text-lg font-medium">
        <h2>See what everyone is up to</h2>
        {allPost.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button className=" bg-teal-400 p-2 rounded-md shadow-md shadow-black">
                {post.comments?.length > 0 ? post.comments?.length : 0} Comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  );
}
